import streamlit as st
import pandas as pd
import io

def show_export_page(df: pd.DataFrame):
    st.markdown("### 💾 Export Cleaned Dataset")
    st.markdown("Download your finalized data for external use.")
    
    # Export Settings
    c1, c2 = st.columns([3, 1])
    
    with c1:
        file_name = st.text_input("File Name (without extension)", value="cleaned_dataset_final")
    
    with c2:
        export_format = st.selectbox("Export Format", ["CSV", "Excel"])
    
    # Generate Download Buffer
    if export_format == "CSV":
        # Convert to CSV in memory
        csv_buffer = df.to_csv(index=False).encode('utf-8')
        
        st.download_button(
            label="⬇️ Download CSV File",
            data=csv_buffer,
            file_name=f"{file_name}.csv",
            mime="text/csv",
            help="Download the cleaned dataset as a standard CSV file."
        )
        
    elif export_format == "Excel":
        try:
            # Convert to Excel in memory using BytesIO
            excel_buffer = io.BytesIO()
            with pd.ExcelWriter(excel_buffer, engine='openpyxl') as writer:
                df.to_excel(writer, index=False, sheet_name='Cleaned Data')
            excel_data = excel_buffer.getvalue()
            
            st.download_button(
                label="⬇️ Download Excel File",
                data=excel_data,
                file_name=f"{file_name}.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                help="Download the cleaned dataset as an Excel spreadsheet."
            )
        except ImportError:
            st.error("Missing dependency: 'openpyxl' is required to export to Excel. Please run `pip install openpyxl`.")

    st.divider()
    
    st.markdown("### 📜 Export Transformation Report")
    st.markdown("Download a reproducible recipe detailing every operation, filter, and cleaning step you just performed.")
    
    if not st.session_state.get("transformation_logs"):
        st.info("No cleaning transformations have been logged yet.")
        return

    r1, r2 = st.columns([3, 1])
    with r1:
        report_name = st.text_input("Report Name", value="transformation_recipe")
    with r2:
        report_format = st.selectbox("Report Format", ["JSON Recipe", "Python Script Snippet"])

    # Create safe logs (without raw dataframes inside) for serialization
    raw_logs = st.session_state["transformation_logs"]
    safe_logs = []
    import copy
    for log in raw_logs:
        safe_log = {k: v for k, v in log.items() if k != "df_snapshot"}
        safe_logs.append(safe_log)

    if report_format == "JSON Recipe":
        import json
        json_data = json.dumps(safe_logs, indent=4, default=str).encode('utf-8')
        st.download_button(
            label="⬇️ Download JSON Recipe",
            data=json_data,
            file_name=f"{report_name}.json",
            mime="application/json",
            help="Download as structured JSON data."
        )
    elif report_format == "Python Script Snippet":
        script_lines = [
            "import pandas as pd",
            "import numpy as np",
            "import re",
            "",
            "# " + "="*50,
            "# AUTOMATED DATA CLEANING RECIPE",
            "# Generated by Call of Data (Streamlit Application)",
            "# " + "="*50,
            "",
            "def _smart_parse_numeric(value):",
            "    if pd.isna(value) or value == '': return np.nan",
            "    s = str(value).strip().lower()",
            "    match_ft_in = re.search(r\"(\\d+)'\\s*(\\d+)\\\"?\", s) or re.search(r\"(\\d+)\\s*ft\\s*(\\d+)\\s*in\", s)",
            "    if match_ft_in:",
            "        try: return float(match_ft_in.group(1)) * 12 + float(match_ft_in.group(2))",
            "        except: pass",
            "    match_frac_mixed = re.search(r\"(\\d+)\\s+(\\d+)/(\\d+)\", s)",
            "    if match_frac_mixed:",
            "        try: return float(match_frac_mixed.group(1)) + (float(match_frac_mixed.group(2)) / float(match_frac_mixed.group(3)))",
            "        except: pass",
            "    match_frac_simple = re.match(r\"^(\\d+)/(\\d+)$\", s)",
            "    if match_frac_simple:",
            "        try: return float(match_frac_simple.group(1)) / float(match_frac_simple.group(2))",
            "        except: pass",
            "    if s.endswith('%'):",
            "        try: return float(s.replace('%', '').strip()) / 100",
            "        except: pass",
            "    multiplier = 1",
            "    if s.endswith('k'): multiplier = 1e3",
            "    elif s.endswith('m'): multiplier = 1e6",
            "    elif s.endswith('b'): multiplier = 1e9",
            "    s_clean = re.sub(r\"[^0-9.e\\-]\", '', s)",
            "    try:",
            "        if s_clean: return float(s_clean) * multiplier",
            "    except: pass",
            "    return np.nan",
            "",
            "def reproduce_cleaning(file_path):",
            "    \"\"\"",
            "    Reproduces the exact cleaning pipeline applied in the Call of Data app.",
            "    Simply change 'file_path' to point to your raw CSV file.",
            "    \"\"\"",
            "    print('Loading dataset...')",
            "    df = pd.read_csv(file_path)",
            "    print(f'Loaded {len(df)} rows, {len(df.columns)} columns.')",
            ""
        ]
        
        for i, log in enumerate(safe_logs):
            op = log.get('operation', '')
            cols = log.get('columns', [])
            p = log.get('parameters', {})
            
            script_lines.append(f"    # --- Step {i+1}: {op} ---")
            script_lines.append(f"    # Columns: {', '.join(cols)}")
            
            # ========== DATA TYPES ==========
            if op == "Convert to Datetime":
                for c in cols:
                    script_lines.append(f"    df['{c}'] = pd.to_datetime(df['{c}'], errors='coerce')")
            
            elif op == "Convert to Numeric":
                mode = p.get('mode', 'standard') if isinstance(p, dict) else 'standard'
                for c in cols:
                    if mode == 'smart_parser':
                        script_lines.append(f"    df['{c}'] = df['{c}'].apply(_smart_parse_numeric)")
                    else:
                        script_lines.append(f"    df['{c}'] = df['{c}'].astype(str).str.replace(r'[$€£¥,]', '', regex=True)")
                        script_lines.append(f"    df['{c}'] = pd.to_numeric(df['{c}'], errors='coerce')")
            
            elif op == "Convert to Categorical":
                for c in cols:
                    script_lines.append(f"    df['{c}'] = df['{c}'].astype('category')")
            
            # ========== MISSING VALUES ==========
            elif op == "Drop rows with missing values":
                script_lines.append(f"    df = df.dropna(subset={cols})")
            
            elif op == "Drop Columns by Threshold":
                script_lines.append(f"    df = df.drop(columns={cols}, errors='ignore')")
            
            elif "Fill Missing" in op:
                method = p.get('method', '') if isinstance(p, dict) else ''
                fill_val = p.get('fill_value', None) if isinstance(p, dict) else None
                for c in cols:
                    if method == 'mean':
                        script_lines.append(f"    df['{c}'] = df['{c}'].fillna(df['{c}'].mean())")
                    elif method == 'median':
                        script_lines.append(f"    df['{c}'] = df['{c}'].fillna(df['{c}'].median())")
                    elif method == 'mode':
                        script_lines.append(f"    df['{c}'] = df['{c}'].fillna(df['{c}'].mode()[0])")
                    elif method == 'forward fill':
                        script_lines.append(f"    df['{c}'] = df['{c}'].fillna(method='ffill')")
                    elif method == 'backward fill':
                        script_lines.append(f"    df['{c}'] = df['{c}'].fillna(method='bfill')")
                    elif method == 'constant' and fill_val is not None:
                        if isinstance(fill_val, (int, float)):
                            script_lines.append(f"    df['{c}'] = df['{c}'].fillna({fill_val})")
                        else:
                            script_lines.append(f"    df['{c}'] = df['{c}'].fillna('{fill_val}')")
            
            # ========== DUPLICATES ==========
            elif op.startswith("Remove Duplicates"):
                keep = p.get('keep', 'first') if isinstance(p, dict) else 'first'
                mode = p.get('mode', 'Full row') if isinstance(p, dict) else 'Full row'
                if mode == "Full row":
                    script_lines.append(f"    df = df.drop_duplicates(keep='{keep}')")
                else:
                    script_lines.append(f"    df = df.drop_duplicates(subset={cols}, keep='{keep}')")
            
            # ========== COLUMNS ==========
            elif op == "Drop Columns":
                script_lines.append(f"    df = df.drop(columns={cols}, errors='ignore')")
            
            elif op == "Rename Columns":
                renames = p.get('renames', {}) if isinstance(p, dict) else {}
                script_lines.append(f"    df = df.rename(columns={renames})")
            
            elif op == "Create Column (Formula)":
                col_name = p.get('col_name', 'new_col') if isinstance(p, dict) else 'new_col'
                formula = p.get('formula', '') if isinstance(p, dict) else ''
                script_lines.append(f"    # Formula used: {formula}")
                script_lines.append(f"    # NOTE: Formula references internal column names from the app.")
                script_lines.append(f"    # Verify column names match your dataset before running.")
                formula_clean = formula.replace("working_df", "df")
                script_lines.append(f"    df['{col_name}'] = {formula_clean}")
            
            elif op == "Numeric Binning":
                strategy = p.get('strategy', 'Equal Width') if isinstance(p, dict) else 'Equal Width'
                bins = p.get('bins', 5) if isinstance(p, dict) else 5
                source_col = p.get('source_col', cols[0] if cols else 'col') if isinstance(p, dict) else cols[0]
                bin_col_name = cols[0] if cols else f"{source_col}_Binned"
                if strategy == "Equal Width":
                    script_lines.append(f"    df['{bin_col_name}'] = pd.cut(df['{source_col}'], bins={bins}).astype(str)")
                else:
                    script_lines.append(f"    df['{bin_col_name}'] = pd.qcut(df['{source_col}'], q={bins}, duplicates='drop').astype(str)")
            
            # ========== NUMERIC CLEANING ==========
            elif op == "Remove Outlier Rows":
                for c in cols:
                    script_lines.append(f"    # Ensure numeric type")
                    script_lines.append(f"    if not pd.api.types.is_numeric_dtype(df['{c}']): df['{c}'] = df['{c}'].apply(_smart_parse_numeric)")
                    script_lines.append(f"    q1_{c} = df['{c}'].quantile(0.25)")
                    script_lines.append(f"    q3_{c} = df['{c}'].quantile(0.75)")
                    script_lines.append(f"    iqr_{c} = q3_{c} - q1_{c}")
                    script_lines.append(f"    df = df[~((df['{c}'] < q1_{c} - 1.5 * iqr_{c}) | (df['{c}'] > q3_{c} + 1.5 * iqr_{c}))]")
            
            elif op == "Cap Outliers":
                lower = p.get('lower', None) if isinstance(p, dict) else None
                upper = p.get('upper', None) if isinstance(p, dict) else None
                for c in cols:
                    script_lines.append(f"    if not pd.api.types.is_numeric_dtype(df['{c}']): df['{c}'] = df['{c}'].apply(_smart_parse_numeric)")
                    if lower is not None and upper is not None:
                        script_lines.append(f"    df['{c}'] = df['{c}'].clip(lower={lower}, upper={upper})")
                    else:
                        script_lines.append(f"    q1 = df['{c}'].quantile(0.25)")
                        script_lines.append(f"    q3 = df['{c}'].quantile(0.75)")
                        script_lines.append(f"    iqr = q3 - q1")
                        script_lines.append(f"    df['{c}'] = df['{c}'].clip(lower=q1 - 1.5*iqr, upper=q3 + 1.5*iqr)")
            
            elif op.startswith("Scale/Normalize"):
                method = p.get('method', '') if isinstance(p, dict) else ''
                for c in cols:
                    script_lines.append(f"    if not pd.api.types.is_numeric_dtype(df['{c}']): df['{c}'] = df['{c}'].apply(_smart_parse_numeric)")
                    if 'Min-Max' in method or 'Min-Max' in op:
                        script_lines.append(f"    df['{c}'] = (df['{c}'] - df['{c}'].min()) / (df['{c}'].max() - df['{c}'].min())")
                    elif 'Z-Score' in method or 'Z-Score' in op:
                        script_lines.append(f"    df['{c}'] = (df['{c}'] - df['{c}'].mean()) / df['{c}'].std()")
            
            # ========== CATEGORICAL ==========
            elif op == "Standardize Text":
                trim = p.get('trim', False) if isinstance(p, dict) else False
                lower = p.get('lower', False) if isinstance(p, dict) else False
                title = p.get('title', False) if isinstance(p, dict) else False
                for c in cols:
                    if trim:
                        script_lines.append(f"    df['{c}'] = df['{c}'].str.strip()")
                    if lower:
                        script_lines.append(f"    df['{c}'] = df['{c}'].str.lower()")
                    if title:
                        script_lines.append(f"    df['{c}'] = df['{c}'].str.title()")
            
            elif op == "Value Mapping":
                mapping = p.get('mapping', {}) if isinstance(p, dict) else {}
                replace_unmatched = p.get('replace_unmatched', False) if isinstance(p, dict) else False
                for c in cols:
                    script_lines.append(f"    df['{c}'] = df['{c}'].replace({mapping})")
                    if replace_unmatched:
                        mapped_vals = list(mapping.values())
                        script_lines.append(f"    _mapped_vals = {mapped_vals}")
                        script_lines.append(f"    df['{c}'] = df['{c}'].apply(lambda x: x if pd.isna(x) or x in _mapped_vals else 'Other')")
            
            elif op == "Rare Grouping":
                rare_cats = p.get('rare_categories', []) if isinstance(p, dict) else []
                for c in cols:
                    script_lines.append(f"    _rare = {rare_cats}")
                    script_lines.append(f"    df['{c}'] = df['{c}'].apply(lambda x: 'Other' if x in _rare else x)")
            
            elif op == "One-Hot Encoding":
                for c in cols:
                    script_lines.append(f"    _dummies = pd.get_dummies(df['{c}'], prefix='{c}').astype(int)")
                    script_lines.append(f"    df = pd.concat([df.drop(columns=['{c}']), _dummies], axis=1)")
            
            # ========== VALIDATION ==========
            elif op == "Remove Validation Violations":
                rules = p.get('rules', []) if isinstance(p, dict) else []
                if rules:
                    script_lines.append("    # Apply validation filtering")
                    script_lines.append("    _v_mask = pd.Series([False] * len(df), index=df.index)")
                    for r in rules:
                        r_type = r['type']
                        r_col = r['column']
                        if r_type == "Numeric Range":
                            script_lines.append(f"    _v_mask |= (df['{r_col}'] < {r['min']}) | (df['{r_col}'] > {r['max']})")
                        elif r_type == "Allowed Categories":
                            _allowed = [str(a).lower() for a in r['allowed']]
                            script_lines.append(f"    _v_mask |= (~df['{r_col}'].astype(str).str.lower().isin({_allowed})) & (df['{r_col}'].notna())")
                        elif r_type == "Non-Null Constraint":
                            script_lines.append(f"    _v_mask |= df['{r_col}'].isna()")
                    script_lines.append("    df = df[~_v_mask]")
            
            # ========== RESHAPE ==========
            elif op == "Transpose Dataset":
                promote = p.get('promote_headers', True)
                if promote:
                    script_lines.append(f"    df = df.set_index(df.columns[0]).T.reset_index()")
                    script_lines.append(f"    df.rename(columns={{'index': 'Observation'}}, inplace=True)")
                else:
                    script_lines.append(f"    df = df.T.reset_index()")
            
            script_lines.append(f"    print('  Step {i+1} done: {op}')")
            script_lines.append("")
        
        script_lines.append("    # Final output")
        script_lines.append("    print(f'Cleaning complete. Final shape: {df.shape[0]} rows, {df.shape[1]} columns.')")
        script_lines.append("    return df")
        script_lines.append("")
        script_lines.append("")
        script_lines.append("if __name__ == '__main__':")
        script_lines.append("    # =============================================")
        script_lines.append("    # CHANGE THE PATH BELOW TO YOUR RAW DATA FILE")
        script_lines.append("    # =============================================")
        script_lines.append("    INPUT_FILE = 'raw_dataset.csv'")
        script_lines.append("    OUTPUT_FILE = 'cleaned_output.csv'")
        script_lines.append("")
        script_lines.append("    cleaned_df = reproduce_cleaning(INPUT_FILE)")
        script_lines.append("    cleaned_df.to_csv(OUTPUT_FILE, index=False)")
        script_lines.append("    print(f'Saved cleaned data to {OUTPUT_FILE}')")
        
        python_data = "\n".join(script_lines).encode('utf-8')
        st.download_button(
            label="⬇️ Download Python Script",
            data=python_data,
            file_name=f"{report_name}.py",
            mime="text/x-python",
            help="Download executable Python script."
        )

    # Explanation section for ordinary users
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown("#### 💡 What do these formats mean?")
    st.info("**What is a JSON Recipe?**\\n\\nJSON (JavaScript Object Notation) is a standard raw data format used silently by computer systems. If you pick this, you get a highly structured text file containing the exact settings and timestamps of your actions. You can hand this file directly to a data engineering team, and their software can automatically read your configuration.")
    st.success("**What is a Python Script Snippet?**\\n\\nPython is the programming language primarily used by Data Scientists. By picking this, our app literally writes real, usable computer code that dynamically mimics your exact actions! You can send this `.py` file to an IT analyst, and they can 'run' your script on their own computer to instantly recreate your cleaned dataset without ever needing to open this app.")
